### ISSUE TITLE
Unable to play more than one sound in a single notebook.

### ISSUE THREAD

**Issue by scfleming** [spacetelescope/astronify#18]
Within a Python notebook, I am unable to run a .play() on more than one sonified object.  The error I get is one where it states "the server must be botted before...", the first call to .play() works as expected, but a second call to another sonified object fails.

**Comment by ceb8** [comment]
I also cannot reproduce this problem..... Hmmmm maybe can you tell me what version of python you are running?

**Comment by scfleming** [comment]
I also can't reproduce it now, maybe it was a weird issue with the notebook I was using while I was developing that got it into a strange stage?  Closing for now, will file new ticket if it crops up again.

**Comment by scfleming** [comment]
Can't reproduce the problem, false alarm.
