### ISSUE TITLE
Handle presence of NaN's correctly.

### ISSUE THREAD

**Issue by scfleming** [spacetelescope/astronify#36]
Currently the Jupyter kernel will die if sonify() is given a set of fluxes with NaN values in it.  These should be filtered out, or the algorithm should be made NaN-safe, depending on our decision for a mitigation strategy.  Kepler/K2 data can sometimes have NaN values in the time array to, so the solution should be applied to both the time and flux axes.

**Comment by ceb8** [comment]
Fixed as of 0.1 release.
