### ISSUE TITLE
Fix Documentation Navigation Links

### ISSUE THREAD

**Issue by Jenneh** [spacetelescope/astronify#48]
Add links to easily move between docs sections and a link back to the home page within each section. 
Read the Docs side bar currently only shows links within that section, but not for the entire project.

**Comment by OutdatedPine906** [comment]
Hi, can I work on this?

**Comment by scfleming** [comment]
Absolutely!  Feel free to open a pull request.

**Comment by OutdatedPine906** [comment]
Not sure if this is exactly what you were looking for. Let me know if you need me to try to clean this up a bit.

The image below is what it will look like if #53 gets merged in.
![example_nav](https://user-images.githubusercontent.com/22628086/113520365-94c0e280-9560-11eb-82d1-171eaf72aa03.png)
